---
title: Binomial model predictions
date: Jan 28, 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path='figs/', # fig.width=12, fig.height=8, f
                      echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(lme4)
library(jtools)
library(glue)

options(
    "summ-model.info"=FALSE, 
    "summ-model.fit"=FALSE, 
    "summ-re.table"=FALSE, 
    "summ-groups.table"=FALSE,
    "jtools-digits"=3
)
update_geom_defaults("line", list(size = 1.2))

RED =  "#E41A1C" 
BLUE =  "#377EB8" 
GREEN =  "#4DAF4A" 
PURPLE =  "#984EA3" 
ORANGE =  "#FF7F00" 
YELLOW =  "#FFDD47" 
theme_set(theme_classic(base_size = 18))
kable = knitr::kable
```

```{r}
read_sim = function(name) {read_csv(glue("../model/results/sim_{name}.csv")) %>% mutate(name=!!name)}
trials = bind_rows(read_sim("optimal"), read_sim("random")) %>% mutate(
    outcome = factor(outcome, levels=c(-1, 1, 2), labels=c("timeout", "low", "high")),
    fix_prop_diff = 2 * (fix_prop - 0.5) 
)
optimal = filter(trials, name=="optimal")
random = filter(trials, name=="random")
```

# Fixation proportions

```{r}
ggplot(trials, aes(vd, fix_prop, color=name, group=name)) + stat_summary(geom="line")
```

## Regressions

### Optimal
```{r}
lm(fix_prop ~ step_size + difficulty + switch_cost + miss_cost + outcome + v0 + vd + rt, 
    data=optimal)  %>% summ(scale=TRUE)
```

### Random
```{r}
lm(fix_prop_diff ~ step_size + difficulty + outcome + v0 + vd + rt, 
    data=random) %>% summ(scale=TRUE)
```


```{r}
# glm(outcome == 'high' ~ fix_prop, family=binomial, data=filter(trials, outcome != "timeout")) %>% summ
lm(outcome == 'high' ~ fix_prop, data=filter(trials, outcome != "timeout")) %>% summ(scale=TRUE)
```

## Is there any case where fix_prop is less than 0.5?

```{r}
optimal %>% 
    group_by(step_size, difficulty, switch_cost, miss_cost, v0, vd) %>% 
    summarise(fix_prop=mean(fix_prop)) %>% 
    with(mean(fix_prop > 0))
```

No





