
# Alternative time courses

```{r, alt-time-course, fig.width=WIDTH, fig.height=2.9}
unroll_time = function(long) {
    long %>% 
        group_by(trial_id) %>%
        mutate(n_step = diff(c(0, round(cumsum(duration)/100)))) %>% 
        uncount(n_step) %>%
        group_by(trial_id) %>% 
        mutate(time = 100*row_number())
}

long %>% 
    unroll_time %>% 
    drop_na(strength_diff) %>% 
    ggplot(aes(time, fix_stronger, group = strength_diff, color=strength_diff)) +
    geom_smooth(se=F) + 
    ylim(0, 1) +
    facet_grid(~name) +
    labs(x="Time in ", y="Probability Fixate\nStronger Cue", color="Strength Difference") +
    geom_hline(yintercept=0.5) +
    theme(legend.position="top")
```

```{r, split-time-course, fig.width=WIDTH, fig.height=2.9}
long %>% 
    filter(between(n_pres, 2, 5)) %>% 
    left_join(select(human, trial_id, n_pres)) %>% 
    normalized_timestep %>% 
    # drop_na(strength_diff) %>% 
    ggplot(aes(normalized_timestep/100, fix_stronger, color = factor(n_pres))) +
    geom_smooth(se=F) + 
    ylim(0, 1) +
    facet_grid(~name) +
    labs(x="Normalized Time", y="Probability Fixate\nStronger Cue") +
    geom_hline(yintercept=0.5) + 
    theme(legend.position="top") + 
    scale_colour_manual(values=c(
        "#F3F1DD", "#F7DAAF", "#F7AF9D", "#C08497"
    ), aesthetics=c("fill", "colour"), name="")

fig(w=6)

```

# Violin fixation durations
```{r}
long %>% 
    filter(name == "Human") %>% 
    filter(presentation < 6) %>% 
    filter(last_fix==0) %>% 
    ggplot(aes(presentation, duration, group=as_factor(presentation))) +
    geom_violin()
```

