---
title: Binomial model predictions
date: "`r Sys.Date()`"
author: "fredcallaway"
output:
  rmdformats::robobook:
    code_folding: hide
    self_contained: true
---

```{r setup, include=FALSE}
source("setup.r")

read_sim = function(name) {
    read_csv(glue("../model/results/sim_{name}.csv")) %>% mutate(name=!!name)
}

raw_df = bind_rows(read_sim("optimal"), read_sim("rand_gamma")) 
```


```{r}
noise_sd = .01
both_models = raw_df %>% 
    group_by(name) %>% 
    mutate(
        strength_first = scale(scale(strength_first) + rnorm(n(), sd=noise_sd)),
        strength_second = scale(scale(strength_second) + rnorm(n(), sd=noise_sd)),
        correct = outcome != -1,
        presentation_times = map(presentation_times, fromJSON),
        rt = duration_first + duration_second,
        prop_first = duration_first / rt,
        rel_present = duration_first - duration_second,
        first_pres_time = map_dbl(presentation_times, 1, .default=NaN),
        second_pres_time = map_dbl(presentation_times, 2, .default=NaN),
        choose_first = outcome == 1,
        n_pres = lengths(presentation_times),
        odd_pres = mod(n_pres, 2) == 1,
        rel_strength = strength_first - strength_second,
        # strength_first_bin = cut(strength_first, 5, ordered=T),
        # strength_second_bin = cut(strength_second, 5, ordered=T),
        rt=rt*250,
        rel_present=rel_present*250,
        duration_first=duration_first*250,
        duration_second=duration_second*250,
        first_pres_time=first_pres_time*250,
        second_pres_time=second_pres_time*250,
    )

optimal = filter(both_models, name=="optimal")
random = filter(both_models, name=="rand_gamma")
human = read_csv("human_multi.csv")
human$name = "human"
df = bind_rows(both_models, human)
mean(optimal$correct)
```

## Fixation proportion by relative memory strength
```{r,fig.width=7.5, fig.height=3}
df %>% 
    filter(n_pres >= 2) %>% 
    ggplot(aes(rel_strength, prop_first)) + geom_smooth(se=F, method="lm") + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5) + facet_wrap(~name)

random %>% lm(prop_first ~ rel_strength, data=.) %>% summ
```

### With extra motor time
```{r,fig.width=7.5, fig.height=3}
ndt = 1000
df %>% 
    mutate(
        rt = rt + ndt,
        duration_first = duration_first + if_else(n_pres %% 2 == 1, ndt, 0),
        prop_first = duration_first / rt,
    ) %>% 
    filter(n_pres >= 2) %>% 
    ggplot(aes(rel_strength, prop_first)) + geom_smooth(se=F, method="lm") + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5) + facet_wrap(~name)

random %>% lm(prop_first ~ rel_strength, data=.) %>% summ
```

### Split by number of presentations
```{r,fig.width=7.5, fig.height=3}
df %>% 
    mutate(last_pres = if_else(n_pres %% 2 == 1, "first", "second")) %>% 
    filter(n_pres >= 2) %>% 
    ggplot(aes(rel_strength, prop_first, color=last_pres)) + geom_smooth(se=F, method="lm") + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5) + facet_wrap(~name)

random %>% lm(prop_first ~ rel_strength, data=.) %>% summ
```

```{r}
df %>% 
    filter(n_pres >= 2) %>% 
    filter(n_pres < 5) %>% 
    ggplot(aes(rel_strength, prop_first, color=factor(n_pres))) + geom_smooth(se=F) + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5) + facet_wrap(~name) +
    theme(legend.position="top")

df %>% 
    filter(n_pres < 8) %>% 
    ggplot(aes(n_pres, rel_strength)) +
    stat_summary(fun.data=mean_cl_boot, bins=10) +
    facet_wrap(~name)

df %>% 
    filter(n_pres < 8) %>% 
    ggplot(aes(n_pres, prop_first)) +
    stat_summary(fun.data=mean_cl_boot, bins=10) +
    facet_wrap(~name)
```


## First fixation duration by first fixated item strength
```{r,fig.width=7.5, fig.height=3}
df %>% 
    filter(n_pres >= 2) %>% 
    ggplot(aes(strength_first, first_pres_time)) + geom_smooth(se=F) + facet_wrap(~name)
```


## Second fixation duration
```{r,fig.width=7.5, fig.height=3}
df %>% 
    filter(n_pres > 2) %>% 
    ggplot(aes(strength_second, second_pres_time)) + geom_smooth(se=F) + facet_wrap(~name)

df %>% 
    filter(n_pres > 2) %>% 
    ggplot(aes(strength_first, second_pres_time)) + geom_smooth(se=F) + facet_wrap(~name)

```

### Split by which target is remembered

```{r,fig.width=7.5, fig.height=3}
ggplot(df, aes(strength_first, first_pres_time, color=choose_first)) + 
    geom_smooth() + facet_wrap(~name)
```

```{r,fig.width=7.5, fig.height=3}
df %>% ggplot(aes(rel_strength, prop_first, color=factor(outcome), group=factor(outcome))) + 
    geom_smooth() + facet_wrap(~name)
```


## Choice probability

Conditioning on remembering a target, how likely is the first seen one to be remembered?

```{r,fig.width=7.5, fig.height=3}
df %>% filter(correct) %>% mutate(
    strength_first_bin = cut(strength_first, 5, ordered=T)
) %>% ggplot(aes(rel_strength, as.numeric(choose_first), color=strength_first_bin)) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), formula=y~x, se=F) + facet_wrap(~name) +
    ylab("p(remember first seen)")
```






