---
title: Familiarity and memory strength
date: "`r Sys.Date()`"
author: "fredcallaway"
output:
  rmdformats::robobook:
    code_folding: hide
    self_contained: true
  output:
    pdf_document:
      latex_engine: xelatex
---


```{r setup, include=FALSE}
source("setup.r")

VERSIONS = c('v7.1')

load_data = function(type) {
    VERSIONS %>% 
    map(~ read_csv(glue('../data/{.x}/{type}.csv'))) %>% 
    bind_rows
}

participants = load_data('participants')

afc = load_data('afc') %>% 
    group_by(wid) %>% 
    mutate(
        trial_num = seq(1:n()),
        log_afc_rt = log(rt),
        presentation = (trial_num-1) %/% 40 + 1
    ) %>% 
    filter(!practice) %>% select(-practice)

afc_scores = afc %>% 
    filter(block > 1) %>%  ## CRITICAL DECISION
    group_by(wid, target) %>% 
    summarise(raw_strength = -mean(log(rt))) %>%
    group_by(wid) %>% 
    mutate(
        strength = scale(raw_strength),
    ) %>% rename(image=target)

recognition = load_data('recognition') %>% 
    left_join(afc_scores, c("wid", "image"))  %>% 
    group_by(wid) %>% 
    mutate(
        trial_num = row_number(),
        rt_z = scale(rt)
    )
```

# Accuracy

```{r}
recognition %>% 
    filter(kind == "old") %>% 
    ggplot(aes(strength, as.numeric(kind == response))) +
    geom_smooth() + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5)
```

# Reaction time

```{r}
X = recognition %>% 
    filter(kind == "old") %>% 
    filter(response == "old") 

X %>% ggplot(aes(strength, rt)) +
    geom_smooth(geom="line", method="lm") + 
    stat_summary_bin(fun.data=mean_cl_boot, bins=5) +
    labs(x="Memory Strength", y="Recognition RT")

X %>% lmer(rt ~ strength + (1 | wid), data=.) %>% summ

```

```{r}
X %>% 
    mutate(rt_z = scale(rt)) %>% 
    ggplot(aes(strength, rt_z, group=wid)) +
    geom_smooth(method="lm", se=F, color="black", group=0, size=2) + 
    geom_smooth(method="lm", se=F, alpha=0.1) + 
    labs(x="Memory Strength", y="Recognition RT")

X %>% lmer(rt ~ strength + (strength | wid), data=.) %>% summ
```
