---
title: Stopping model predictions
date: "`r Sys.Date()`"
author: "fredcallaway"
output:
  rmdformats::robobook:
    code_folding: hide
    self_contained: true
  output:
    pdf_document:
      latex_engine: xelatex
---


```{r setup, include=FALSE}
source("setup.r")

df = read_csv("../model/results/stopping_sim.csv")

df %>% 
    filter(give_up) %>% 
    ggplot(aes(p, n_step, color=as.factor(miss_cost))) +
    stat_summary(fun=mean, geom="line") +
    labs(x="Memory Strength", y="Time of Giving up", color="Error Cost")
```

```{r}
df %>% 
    ggplot(aes(p, as.numeric(give_up), color=as.factor(miss_cost))) +
    stat_summary(fun=mean, geom="line") +
    theme(legend.position="top") + 
    labs(x="Memory Strength", y="Probability of Giving up", color="Error Cost")

```

```{r,fig.width=7.5, fig.height=2.5}
df %>% 
    filter(p %in% c(.05, .1, .2)) %>% 
    filter(miss_cost == 100) %>% 
    filter(give_up) %>% 
    ggplot(aes(n_step)) + 
    geom_bar(aes(y=..count../sum(..count..)), position="identity")  +
    facet_wrap(~p, labeller=label_glue("p = {p}")) + 
    labs(x="Time", y="Proportion Giving Up") + 
    xlim(0, 15)
```
