---
title: Giving up (v6.0 - v6.1)
date: "`r Sys.Date()`"
author: "fredcallaway"
output:
  rmdformats::robobook:
    code_folding: hide
    self_contained: true
---


```{r setup, include=FALSE}
source("setup.r")

VERSIONS = c('v6.3')
# VERSIONS = c('v4.0')
# VERSIONS = c('v2.0', 'v2.0B')

load_data = function(type) {
    VERSIONS %>% 
    map(~ read_csv(glue('../data/{.x}/{type}.csv'))) %>% 
    bind_rows
}

pretest = load_data('simple-recall') %>% 
    filter(!practice) %>% 
    mutate(
        response_type = factor(response_type, 
            levels=c("correct", "intrusion", "other", "timeout", "empty"),
            # labels=c("Correct", "Intrusion", "Other")
        ),
        total_time = rt + type_time,
        correct = response_type == "correct"
    ) %>% mutate(
        base_rt = rt,
        rt = typing_rt
    )

all_trials = load_data('simple-recall-penalized') %>% 
    filter(!practice) %>% 
    mutate(
        response_type = factor(response_type, 
            levels=c("correct", "intrusion", "other", "timeout", "empty"),
            # labels=c("Correct", "Intrusion", "Other")
        ),
        total_time = rt + type_time,
        correct = response_type == "correct"
    ) %>% mutate(
        base_rt = rt,
        rt = typing_rt
    )

strengths = pretest %>% 
    filter(block == max(block)) %>% 
    mutate(strength =  5 * correct - log(rt)) %>%
    group_by(wid, word) %>% 
    summarise(strength = mean(strength)) %>%
    group_by(wid) %>%
    mutate(strength = zscore(strength))

all_trials = all_trials %>% left_join(strengths)

# x1 = afc %>% 
#     group_by(wid, word) %>% 
#     summarise(afc_accuracy = mean(correct))

# x2 = afc %>% 
#     filter(correct) %>% 
#     group_by(wid, word) %>% 
#     summarise(afc_rt = mean(rt))

# all_trials = inner_join(all_trials, inner_join(x1, x2))
```

# Data

### Exclusions

```{r}
trials = all_trials
# trials = all_trials %>% group_by(wid) %>% filter(mean(correct) > 0.25)
trials = trials %>%
    filter(rt > 50) %>%
    group_by(wid) %>% 
    filter(n() >= 35) %>% 
    filter(between(mean(response_type == "empty"), .2, .8))


n_exclude = length(unique(all_trials$wid)) - length(unique(trials$wid))
N = length(unique(trials$wid))

nt = nrow(trials)
max_rt = with(trials, mean(rt, na.rm=TRUE) + 5 * sd(rt, na.rm=TRUE))
# trials = filter(trials, rt < max_rt)
n_trial = nrow(trials)
n_drop_rt = nt - n_trial

# trials %<>% mutate(
#     log_afc_rt = log(afc_rt),
#     recall_rt = rt,
#     log_recall_rt = log(rt)
# )

trials$name = "Human"
# trials %>% select(wid, rt, correct, afc_rt, afc_accuracy) %>% write_csv("../model/tofit/simple.csv")
```

- Excluding `r n_exclude` participants who gave orrect resonses on fewer than 25% of recall trials or responded in under 50ms on more than one trial (indicating a recording error), leaving `r N` participants in the analysis.
<!-- - Excluding `r sum(afc_drop_rt)` AFC reaction times more than 5 sds from the mean. -->
<!-- - Dropping `r n_drop_rt` recall trials with reaction times over more than 3 sds above the mean (more than `r round(max_rt/1000, 1)` seconds), leaving `r n_trial` trials in the analysis. -->


## Foo


```{r}
trials %>% 
    count(wid, response_type) %>% 
    pivot_wider(names_from=response_type, values_from=n)

trials %>% 
    filter(response_type == "empty") %>% 
    regress(strength, rt) #plot

trials %>% 
    filter(response_type == "empty") %>% 
    ggplot(aes(strength, rt, group=wid)) +
    geom_smooth(method="lm")

trials %>% 
    mutate(empty=1 * (response_type == "empty")) %>% 
    regress(strength, empty) #plot

```

```{r}
trials %>% 
    ggplot(aes(response_type)) +
    geom_bar()

trials %>% 
    group_by(wid) %>% 
    summarise(n_empty = sum(response_type == "empty"))trials %>% 

trials %>% 
    group_by(wid) %>% 
    count(response_type) %>% 
    pivot_wider(names_from=response_type, values_from=n)
```


# Model Prediction()
```{r}
df = read_csv("../model/results/stopping_sim.csv")

df %>% 
    filter(give_up) %>% 
    ggplot(aes(p, n_step, color=as.factor(miss_cost))) +
    stat_summary(fun=mean, geom="line") +
    labs(x="Memory Strength", y="Time of Giving up", color="Error Cost")
```

```{r}
df %>% 
    ggplot(aes(p, as.numeric(give_up), color=as.factor(miss_cost))) +
    stat_summary(fun=mean, geom="line") +
    theme(legend.position="top") + 
    labs(x="Memory Strength", y="Probability of Giving up", color="Error Cost")

```

```{r,fig.width=7.5, fig.height=2.5}
df %>% 
    filter(p %in% c(.05, .1, .2)) %>% 
    filter(miss_cost == 100) %>% 
    filter(give_up) %>% 
    ggplot(aes(n_step)) + 
    geom_bar(aes(y=..count../sum(..count..)), position="identity")  +
    facet_wrap(~p, labeller=label_glue("p = {p}")) + 
    labs(x="Time", y="Proportion Giving Up") + 
    xlim(0, 15)
```