## Power analysis

Power for the RT 

```{r}
library(simr)

groups = trials %>% ungroup() %>% nest_by(wid, .keep=TRUE) %>% with(data)

sample_p = function(N, run_model) {
    data = sample(groups, N, replace=T) %>% 
        map(~ mutate(.x, wid=round(1e10 * runif(1)))) %>%
        bind_rows
    tryCatch(run_model(data), error=function(c) NaN)
}

power_analysis = function(N, n_sim, run_model) {
    results = map(N, ~ replicate(n_sim, sample_p(.x, run_model))) %>% unlist
    expand.grid(
        sim_i = 1:n_sim,
        N = N
    ) %>% 
    rowwise() %>% 
    mutate(
        p = sample_p(N, run_model)
    ) %>% ungroup()
}

N = seq(50, 200, 25)
n_sim = 100

p1 = power_analysis(N, n_sim, . %>% 
    filter(skip) %>% 
    lmer(rt_z ~ pre_correct + (pre_correct|wid), data=.) %>%
    summary %>% with(coefficients[2,5] )
)

N = seq(25, 150, 25)
n_sim = 100

p2 = power_analysis(N, n_sim, . %>% 
    filter(skip) %>% 
    lmer(rt_z ~ judgement + (judgement|wid), data=.) %>%
    summary %>% with(coefficients[2,5] )
)

```

```{r}
p2 %>% 
    group_by(N) %>% 
    summarise(power=mean(p<.05))

```